name: Unit Tests

on:
  push: 
    branches: ['main']
    paths: [ '**.ts', '**.js', 'src/**', 'test/**']
  pull_request:
    branches: ['main']
    paths: [ '**.ts', '**.js', 'src/**', 'test/**']

jobs:
  test:
    name: Test the Code with ${{matrix.node-version}} on ${{matrix.machine}}

    strategy:
      matrix:
        node-version: [ '20.x', '18.x' ]
        machine: ['ubuntu-latest']

    runs-on: ${{matrix.machine}}
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node environment wth ${{matrix.node-version}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.node-version}}

    - name: Install the dependencies
      run : npm ci

    - name: Run Unit Tests
      run : npm test